### ISSUE TITLE
Crashing with multiple entries error

### ISSUE THREAD

**Issue by ghost** [Mrthomas20121/TinkerFirmaCraft#10]
My game crashes with this error.
> The game crashed whilst initializing game
> Error: java.lang.IllegalArgumentException: Multiple entries with same key: tfc_tinker=FMLMod:tfc_tinker{1.3.0} and tfc_tinker=FMLMod:tfc_tinker{1.2.6}. To index multiple values under a key, use Multimaps.index.

I checked the mods file and I only saw tfc_tinkers-1.3.0.jar file. I also tried with another Minecraft instance, but I got the same error.

**Comment by Mrthomas20121** [comment]
that's weird, i'll investigate
