### ISSUE TITLE
Crash when TinkerSmeltery=false in TinkerModules.cfg

### ISSUE THREAD

**Issue by mechobree** [Mrthomas20121/TinkerFirmaCraft#11]
**Describe the bug/crashreport**
When you go into TinkerModules.cfg to disable the tinkers construct smeltery (I want to use a different thing for smelting in my modpack) the game crashes.

**To Reproduce**
1. Set the config option B:TinkerSmeltery=false inside of TinkerModules.cfg

**Expected behavior**
Game should load.

**Crash report Link**
https://pastebin.com/vbdetnXj

**Version**
 - Minecraft: 1.12.2
 - TinkerFirmaCraft: 1.4.4
 - Forge: 14.23.5.2854

**Comment by Mrthomas20121** [comment]
the crash is not related the smeltery though, also please use the latest release/version of the mod.

**Comment by mechobree** [comment]
Sorry, I am on the latest version 1.4.4, I put down tfc's version number by mistake, whoops.
Even if it's not related to the smeltery, it works and loads just fine when that module is set to true.
