### ISSUE TITLE
Grout knapping does not consume Grout Balls

### ISSUE THREAD

**Issue by Lgmrszd** [Mrthomas20121/TinkerFirmaCraft#12]
**Describe the bug/crashreport**
Grout knapping does not consume Grout Balls. That's it

**To Reproduce**
Knap some unfired Grout Bricks using Grout Ball
Grout Ball does not get consumed

**Expected behavior**
Grout ball gets consumed

**Screenshots**
No specific screenshots

**Crash report Link**
No crash

**Version**
 - Minecraft: 1.12.2
 - TinkerFirmaCraft: 1.7.9.167
 - Tinkers' Construct: 2.13.0.183
 - TFC Tinkers: 1.5.0
 - Forge: 14.23.5.2854

**Additional mods involved**
Don't think these mods are involved but gonna list them just in case
TFCTech Unofficial: 1.2.15
TFC Metallum: 1.4.0

**Comment by Mrthomas20121** [comment]
2 grout ball should get consued. i'll look into it

**Comment by ACGaming** [comment]
Also reported in my modpack: https://www.curseforge.com/minecraft/modpacks/terrafirmacraft-reditus-2/issues/7
