### ISSUE TITLE
Prospector picks don't show ore names while prospecting

### ISSUE THREAD

**Issue by ironsnake345** [Mrthomas20121/TinkerFirmaCraft#19]
As sort of a shortcut into mining, I decided to create a prospector pick using bone. I noticed that it said it "discovered trace amounts of" but the message stopped before saying what I had actually discovered trace amounts of. Every message I get when prospecting doesn't include the name of the mineral found. I thought this was a feature at first, but then I created a vanilla TFC prospector pick, and it freely explains what mineral I'm finding trace amounts or large samples of.

TFC went through some changes to prospecting recently; maybe that affected the prospector picks added by this mod? I confirmed I'm using the most recent version of this mod, as well. If you need anything else from me, let me know.

**Comment by Mrthomas20121** [comment]
will be fixed soon.
