### ISSUE TITLE
here's a new .lang for this mod

### ISSUE THREAD

**Issue by balitely** [Mrthomas20121/TinkerFirmaCraft#21]
Greeting from china!
I made an translation for chinese.
here is the text,and I don't known how to upload them in .lang in github.
please help me to add them into the new version of this mod
Thanks you again!
mod version :tinkers_reforged-1.4.1.jar

file name:
zh_cn.lang

text:
# config
config.tinkers_reforged.enableAlloy=Enable Alloy recipes.
config.tinkers_reforged.manacost=How much mana Livingwood/Livingrock/Manasteel parts cost.
config.tinkers_reforged.fuels=Fuels added by this mod. syntax is : modid:fluid_name:temp:amount:fuel_duration
config.tinkers_reforged.parts_botania=Materials used to create Manasteel, Livingwood, Livingrock parts. syntax is: manasteel:livingwood:livingrock
config.tinkers_reforged.parts_astral=Material used to create starmetal parts.
config.tinkers_reforged.material=Materials to remove list.
config.tinkers_reforged.modules=Modules to disable list. module name is the mod id
config.tinkers_reforged.tools=Enable the Tinkers Reforged tools.
config.tinkers_reforged.tool.gladius=Enable the gladius.
config.tinkers_reforged.tool.club=Enable the club.
config.tinkers_reforged.tool.greatsword=Enable the greatsword.
config.tinkers_reforged.tool.khopesh=Enable the khopesh.
config.tinkers_reforged.tool.knife=Enable the Roots Knife.
config.tinkers_reforged.tool.lightsword=Enable the Lightsword.

# creative tab
itemGroup.tinkers_reforged=工匠再锻

# blocks
tile.tinkers_reforged.kovar_glass.name=科瓦铁镍钴合金玻璃

# items 

#lavium
item.tinkers_reforged.lavium_nugget.name=拉维乌姆粒
item.tinkers_reforged.lavium_ingot.name=拉维乌姆锭
item.tinkers_reforged.lavium_dust.name=拉维乌姆粉
item.tinkers_reforged.lavium_plate.name=拉维乌姆板
item.tinkers_reforged.lavium_gear.name=拉维乌姆齿轮
#qivium
item.tinkers_reforged.qivium_nugget.name=基夫乌姆粒
item.tinkers_reforged.qivium_ingot.name=基夫乌姆锭
item.tinkers_reforged.qivium_dust.name=基夫乌姆粉
item.tinkers_reforged.qivium_plate.name=基夫乌姆板
item.tinkers_reforged.qivium_gear.name=基夫乌姆齿轮
#kovar
item.tinkers_reforged.kovar_nugget.name=科瓦铁镍钴合金粒
item.tinkers_reforged.kovar_ingot.name=科瓦铁镍钴合金锭
item.tinkers_reforged.kovar_ingot.name=科瓦铁镍钴合金粉
item.tinkers_reforged.kovar_plate.name=科瓦铁镍钴合金板
item.tinkers_reforged.kovar_gear.name=科瓦铁镍钴合金齿轮

# Gladius
item.tinkers_reforged.gladius.name=罗马短剑
item.tinkers_reforged.gladius.desc=一把可以给予敌人伤害的阔剑，他还可以减速你的敌人.

# Lightsword
item.tinkers_reforged.light_blade.name=轻剑刃
item.tinkers_reforged.lightsword.name=轻剑
item.tinkers_reforged.lightsword.desc=狼人杀手

# Club
item.tinkers_reforged.club.name=狼牙棒
item.tinkers_reforged.club.desc=一种可以给与你的敌人致命打击的武器
item.tinkers_reforged.club_head.name=狼牙棒头

# Khopesh
item.tinkers_reforged.curved_blade.name=克赫帕什镰形剑刃
item.tinkers_reforged.khopesh.name=克赫帕什镰形剑
item.tinkers_reforged.khopesh.desc=一种古埃及的冷兵器.

# Greatsword
item.tinkers_reforged.great_blade.name=大剑刃
item.tinkers_reforged.greatsword.name=大剑
item.tinkers_reforged.greatsword.desc=一把巨大的，有力的武器.

# runic_knife
item.tinkers_reforged.runic_knife.name=北欧小刀
item.tinkers_reforged.runic_knife.desc=一种曾被用来刮取苔藓的小刀.

# propick
item.tinkers_reforged.propick_head.name=勘矿镐头
item.tinkers_reforged.propick.name=勘矿镐
item.tinkers_reforged.propick.desc=一种用于寻找矿石的镐子.

# Fluids
fluid.infused_iron=熔融灌注铁锭
fluid.material_of_the_sky=熔融天空之锭
fluid.starmetal=熔融星辉锭
fluid.blutonium=熔融蓝钚
fluid.ludicrite=熔融纯镥
fluid.qivium=Molten Qivium
fluid.lavium=Molten Lavium
fluid.kovar=熔融科瓦铁镍钴合金
fluid.osmium=熔融锇
fluid.refined_obsidian=熔融强化黑曜石
fluid.refined_glowstone=熔融强化萤石
fluid.ventium=Molten Ventium
fluid.horizonite=Molten Horizonite
fluid.pyrope=熔融镁铝榴石
fluid.blackquartz=熔融焦黑石英
fluid.enori=熔融铁晶
fluid.palis=熔融青金石水晶
fluid.void=熔融煤晶
fluid.emeradic=熔融绿宝石水晶
fluid.restonia=熔融红石水晶
fluid.diamatine=熔融钻石水晶
fluid.ruby=熔融红宝石
fluid.sapphire=熔融蓝宝石
fluid.peridot=熔融橄榄石
fluid.titanium=熔融钛
fluid.platinum=熔融铂
fluid.aluminum=熔融铝黄铜
fluid.iridium=熔融铱
fluid.amethyst=熔融紫水晶
fluid.aquamarine=熔融海蓝宝石
fluid.magnite=熔融超硝石
fluid.hexcite=熔融白钻石
fluid.waterstone=熔融水之石
fluid.firestone=熔融火之石
fluid.leafstone=熔融叶之石
fluid.thunderstone=熔融雷之石
fluid.sunstone=熔融日之石
fluid.dawnstone=熔融黎明石
fluid.duskstone=Molten Duststone
fluid.thaumium=熔融神秘
fluid.khnumite=熔融克努姆陶

# mining levels
ui.mininglevel.lavium=Lavium

# materials

# common materials
material.ref_ruby.name=红宝石
material.ref_sapphire.name=蓝宝石
material.ref_peridot.name=橄榄石
material.ref_titanium.name=钛
material.ref_platinum.name=铂
material.ref_iridium.name=铱
material.ref_invar.name=殷钢
material.ref_aluminum.name=铝
material.ref_amethyst.name=紫水晶

# thermalfoundation materials
material.ref_enderium.name=末影
material.ref_signalum.name=信素
material.ref_lumium.name=流明

## caver II materials
material.ref_aquamarine.name=海蓝宝石
material.ref_magnite.name=超硝石
material.ref_hexcite.name=白钻石

# naturesaura materials
material.ref_infused_iron.name=灌注铁锭
material.ref_ancient_wood.name=荒古树
material.ref_sky.name=天空之锭

## aa materials
material.ref_blackquartz.name=焦黑石英
material.ref_enori.name=铁晶
material.ref_void.name=煤晶
material.ref_restonia.name=红石水晶
material.ref_emeradic.name=绿宝石水晶
material.ref_diamatine.name=钻石水晶
material.ref_palis.name=青金石水晶

# Appliedenergistic2 materials
material.ref_certus_quartz.name=塞特斯石英水晶
material.ref_fluix_crystal.name=福鲁伊克斯水晶

# Astralsorcery materials
material.ref_starmetal.name=星辉

# Atum 2
material.ref_limestone.name=石灰岩
material.ref_khnumite.name=克奴姆陶

# blueskies
material.ref_ventium.name=Ventium
material.ref_horizonite.name=Horizonite
material.ref_pyrope.name=Pyrope
material.ref_turquoise.name=Turquoise
material.ref_charoite.name=Charoite
material.ref_dioside.name=Diopside

# botania
material.ref_manasteel.name=魔力钢
material.ref_mana_diamond.name=魔力钻石
material.ref_elementium.name=源质钢
material.ref_terrasteel.name=泰拉钢
material.ref_dragonstone.name=龙石
material.ref_livingrock.name=活石
material.ref_livingwood.name=活木
material.ref_dreamwood.name=梦之木
material.red_string.name=红线
material.ref_mana_string.name=蕴魔丝线
material.ref_gaia_spirit.name=盖亚之魂

# Mekanism
material.ref_osmium.name=饿
material.ref_refined_obsidian.name=强化黑曜石
material.ref_refined_glowstone.name=强化萤石

# Roots
material.ref_runestone.name=符文石

# Extreme reactor
material.ref_yellorium.name=黄铀
material.ref_blutonium.name=蓝钚
material.ref_ludicrite.name=纯镥
material.ref_cyanite.name=蓝晶

# pixelmon
material.ref_firestone.name=火之石
material.ref_waterstone.name=水之石
material.ref_leafstone.name=叶之石
material.ref_thunderstone.name=雷之石
material.ref_sunstone.name=日之石
material.ref_dawnstone.name=黎明石
material.ref_duskstone.name=黄昏石
material.ref_crystal.name=水晶

# project red core
material.ref_electrotine.name=蓝石
material.ref_electrotine_alloy.name=蓝石合金
material.ref_red_alloy.name=红石合金

# thaumcraft
material.ref_thaumium.name=神秘

# tinkers reforged
material.ref_lavium.name=Lavium
material.ref_qivium.name=Qivium

# Traits and Modifiers
modifier.ref_signal.name=标志
modifier.ref_signal.desc=§o老兄, 快停止攻击那些苦力怕!§r\n攻击苦力怕使他们爆炸.

modifier.ref_ender.name=末影
modifier.ref_ender.desc=§o别看他们的眼睛!§r\n对末影生物造成双倍伤害.

modifier.ref_enderfestation.name=末影化脓
modifier.ref_enderfestation.desc=§o我真讨厌这些小家伙, 他们到处都是!§r\n挖掘方块时有概率生成一只末影螨.

modifier.ref_bright.name=明亮
modifier.ref_bright.desc=§o太阳赐予我力量!§r\n在太阳底下你的工具得到更多伤害/挖掘速度.

modifier.ref_astral.name=星辉
modifier.ref_astral.desc=§o我在夜晚也能看清楚!§r

modifier.aura_infusion.name=灵气灌注
modifier.aura_infusion.desc=§o这个工具在修复自己？但他在用什么修?§r\n用灵气修复你的工具.

modifier.pyromancy.name=火卜
modifier.pyromancy.desc=§o让火焰净化一切!§r\n暴击时点燃敌人.

modifier.ref_radioactive.name=辐射
modifier.ref_radioactive.desc=§o哦不!§r\n在每个tick你有50%的概率治愈凋零/中毒.

modifier.nuclear_waste.name=核废料
modifier.nuclear_waste.desc=§o核辐射到了每个人的心里?§r\n在你攻击/挖掘方块后得到一个随机的原版效果.

modifier.life_steal.name=生命偷取
modifier.life_steal.desc=§o你想要更多???§r\n从怪物身上吸取生命值.

modifier.ref_refined.name=精炼
modifier.ref_refined.desc=§o没有那么快!§r\n更快的挖掘黑曜石.

modifier.ref_flux.name=通量
modifier.ref_flux.desc=§o他是怎么工作的?§r\n有概率不损耗工具耐久，但也会有概率令你疲劳.

modifier.ref_star_shaped.name=星型
modifier.ref_star_shaped.desc=§o这形状就像个星星!§r\n总是暴击

modifier.ref_villager_love.name=村民之爱
modifier.ref_villager_love.desc=§o我绿了好几天了!§r\n击杀怪物时有概率掉落绿宝石

modifier.ref_curse.name=诅咒
modifier.ref_curse.desc=§o诅咒§r\nChance of resurecting the target.

modifier.ref_rose.name=玫瑰
modifier.ref_rose.desc=§o玫瑰是红色的, 暴力是蓝色的§r\n玻璃有概率掉落染料.

modifier.ref_void.name=真空
modifier.ref_void.desc=§o这看上去就是空的§r\n挖掘方块时掉落虚空物品.

modifier.ref_starry_night.name=星空之夜
modifier.ref_starry_night.desc=§o看那些星星!§r\n晚上给与急迫效果

modifier.ref_carbon.name=碳
modifier.ref_carbon.desc=§o就像石头一样硬§r\n增加工具耐久.

modifier.ref_fey.name=费伊
modifier.ref_fey.desc=§o注视自然!§r\nFey Spirits empowered your tools, giving it a overall boost.

modifier.ref_mana_infusion.name=魔力灌注
modifier.ref_mana_infusion.desc=§o植物魔法真的是个魔法模组!§r\n汲取魔法来修复你的工具.

modifier.ref_mana_boost.name=魔力激发
modifier.ref_mana_boost.desc=§o更多伤害§r\n汲取魔法来造成更多伤害.

modifier.ref_living.name=活的
modifier.ref_living.desc=§这感觉不错!§r\n阻挡攻击可以治愈你.

modifier.ref_rod.name=闪电棒
modifier.ref_rod.desc=§o电闪雷鸣!§r\n击打生物和玩家会在他们所在位置召唤一道闪电.

modifier.ref_teleport.name=传送
modifier.ref_teleport.desc=§o我的东西去哪了?§r\n挖下的方块可以直接传送到你的物品栏内.

modifier.ref_soft.name=柔和
modifier.ref_soft.desc=§o这很海绵§r\n工具挖掘等级降低到铁.

modifier.ref_fast.name=急速
modifier.ref_fast.desc=§o我们得更快!§r\n你的工具拥有更快的速度和更少的耐久.

modifier.ref_backfire.name=火噬
modifier.ref_backfire.desc=§o真烫手§r\n这个工具太烫手了，他会点燃拿上他的玩家.

modifier.ref_leafblower.name=吹叶机
modifier.ref_leafblower.desc=§o现在我才是检举人§r\n站在玻璃上造成双倍伤害.

modifier.ref_crystal_surge.name=晶振
modifier.ref_crystal_surge.desc=§o石~§r\n从水晶处得到掉落物增加.

modifier.ender_star.name=末影之星
modifier.ender_star.desc=§o末影的力量!§r\nall Mobs can drop wither skeleton skulls.

modifier.lens_killer.name=杀手之眼
modifier.lens_killer.desc=§o更多力量!§r\n你的武器造成更高伤害.

modifier.token.name=代币
modifier.token.desc=§oToken Power!§r\nGive one free modifier.

modifier.ref_amber.name=琥珀
modifier.ref_amber.desc=§o闪闪发亮!§r\n增加工具耐久!

modifier.ref_malachite.name=孔雀石
modifier.ref_malachite.desc=§o闪闪发亮!§r\n增加工具耐久!

modifier.ref_tanzanite.name=坦桑石
modifier.tanzanite.desc=§o闪闪发亮!§r\n增加工具耐久!

modifier.ref_topaz.name=黄玉
modifier.ref_topaz.desc=§o闪闪发亮!§r\n增加工具耐久!

modifier.ref_lens_miner.name=矿工之眼
modifier.ref_lens_miner.desc=§oPhysics 101§r\n挖掘方块有概率掉落矿石(任何矿石).

modifier.ref_terrestrial_artifact.name=大地造物
modifier.ref_terrestrial_artifact.desc=§o闪闪发亮!§r\n增加工具耐久!

modifier.ref_shulker_pearl.name=潜影珍珠
modifier.ref_shulker_pearl.desc=§oBetter than an eletra§r\n消除漂浮效果.

modifier.ref_digging.name=挖掘
modifier.ref_digging.desc=提升挖掘速度

**Comment by Mrthomas20121** [comment]
wrong mod.
