### ISSUE TITLE
Crahs after add tinker's addon

### ISSUE THREAD

**Issue by Elthagrim** [Mrthomas20121/TinkerFirmaCraft#28]
**Describe the bug/crashreport**
crahs on load minecraft

**Crash report Link**
https://pastebin.com/QPZzucGc
**Version**
 - Minecraft: : 1.12.2
 - TFC Tinkers : 1.5.6
 - Forge : 14.23.5.2855

**Additional mods involved**
Tinker's compendium

**Comment by ACGaming** [comment]
Known issue, just use Bio Library 1.1.2 for the time being.

**Comment by Elthagrim** [comment]
Thanks, work fine with Bio Library 1.1.2
