### ISSUE TITLE
Only took twenty damn minutes

### ISSUE THREAD

**Issue by WorkShit101** [Mrthomas20121/TinkerFirmaCraft#3]
ALRIGHT So after making an account and all this other fun shit on github. 
Your mod tinkerfirmacraft crashes upon launch. Fix it if you want, it won't be going in my modpack any time soon shoot me an email if ya want when its fixed but fuck this github shit.
[crash-2019-12-08_08.07.07-client.txt](https://github.com/Mrthomas20121/TinkerFirmaCraft/files/3936252/crash-2019-12-08_08.07.07-client.txt)

**Comment by Mrthomas20121** [comment]
You need Tinker construct(mod) which you don't have. when you install a mod without twitch, check the dependencies pages. it show you what you need to install. also you could've just asked on my discord.

**Comment by WorkShit101** [comment]
Well that's embarrassing, swore I had it installed. My bad I'll give it another shot shortly
