### ISSUE TITLE
Game crashes when immersive engineering and Tinkerfirma is loaded together

### ISSUE THREAD

**Issue by Sty2k5** [Mrthomas20121/TinkerFirmaCraft#4]
**Describe the bug/crashreport**
Constantan is already registered and causes an error
**To Reproduce**
load up immersive engineering and Tinkerfirmacraft

**Expected behavior**
game should load

**Screenshots**

**Crash report Link**
post your crash report to pastebin or other sites to help me figure out what is wrong.
(pastebin isnt' working atm but here's the primary line 
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not register Material "constantan": It was already registered by Immersive Engineering
)

**Version**
 - Minecraft: :1.12
 - TinkerFirmaCraft :1.0.3
 - Forge :

**Additional mods involved**
Add any other mods about the problem here(mod:version). Immersive engineering

**Comment by Mrthomas20121** [comment]
Should be fixed in the next release.

**Comment by Mrthomas20121** [comment]
https://www.curseforge.com/minecraft/mc-mods/tinkerfirmacraft/files/2841094 should fix it. lemme know if it crash again
