### ISSUE TITLE
Add TFC Metallum support

### ISSUE THREAD

**Issue by Sty2k5** [Mrthomas20121/TinkerFirmaCraft#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
some of the metals registered by metallum (osmium, aluminum brass etc.) aren't natively registered by TiCon and i'd like to see a hook up therein

**Describe alternatives you've considered**
scripting them in by hand
ignoring the problem
creating a crafting recipe to convert the two

**Additional context**

**Comment by Mrthomas20121** [comment]
Tfc metallum support is planned! right now it only support constantan.

**Comment by Mrthomas20121** [comment]
https://www.curseforge.com/minecraft/mc-mods/tinkerfirmacraft/files/2888768 TinkerFirmaCraft Now have TFC-Metallum support as of 1.1.0
