### ISSUE TITLE
TinkerFirma 1.0.4 SpongeForge server crash.

### ISSUE THREAD

**Issue by yaroslav4167** [Mrthomas20121/TinkerFirmaCraft#7]
**Describe the bug/crashreport**
![8srs](https://user-images.githubusercontent.com/18057310/70835812-f2c73500-1e06-11ea-8e32-221aaedfe995.png)

**To Reproduce**
starting server...
crash...

**Crash report Link**
[link](https://lww.page.link/vcNP)

**Version**
 - Minecraft: : 1.12.2
 - TinkerFirmaCraft : 1.0.4
 - Forge : 14.23.5.2847

**Additional mods involved**
SpongeForge: 1.12.2-2838-7.1.8-RC3960

**Comment by Mrthomas20121** [comment]
This should not happen. i fixed that issue in 1.0.3. will look into it

**Comment by Mrthomas20121** [comment]
Found the bug. should be fixed in the next release.
