### ISSUE TITLE
Crashes when trying to register trait "brittle"

### ISSUE THREAD

**Issue by Pival81** [Mrthomas20121/TinkerFirmaCraft#9]
**Describe the bug/crashreport**
The game crashes because you're trying to register a trait (brittle) that already exists.

**To Reproduce**
Start the game

**Expected behavior**
The game starts

**Screenshots**

**Crash report Link**
https://paste.dimdev.org/yevofososi.mccrash

**Version**
 - Minecraft: : 1.12.2
 - TinkerFirmaCraft : 1.2.6
 - Forge : 14.23.5.2854 

**Additional mods involved**
extra utilities 2 1.9.9, which adds the other brittle trait

**Comment by Mrthomas20121** [comment]
i know what's wrong. should be fixed in the next build.
